### ISSUE TITLE
Option for Gym Probing

### ISSUE THREAD

**Issue by AvatarQAZ** [Noctem/Monocle#113]
In a effort to reduce Captcha can you implement the ability to NOT interact with a gym?

**Comment by quixfz** [comment]
monocle doesn't interact with gyms. the data you see on the map is sent with each request anyway. like when you walk around in the game, you will see all gyms, its color and height (~level). monocle tries to emulate the real game as much as possible, so, this data is around anyway.

**Comment by manolomanila** [comment]
How many captchas/accounts do you get/have?

I'm getting 7-8 captchas per hour with 4 accounts scanning, 19.5 speed. Used to get 12-15 captchas (lately increasing to 15-20) with 12 accounts scanning a larger area with 8 speed.

I've been playing with speed and scan delay, but since you might need more accounts, it seems that the result will be more or less the same.

**Comment by stunnaspinz** [comment]
Best reduction of captchas is to level up the accounts. I have spin spike stops turned on.  I currently have 600 accounts and experience 0 captchas per day.

**Comment by stunnaspinz** [comment]
Spin Pokestops.*

**Comment by manolomanila** [comment]
Thank you, gonna turn it on and test it!

**Comment by AvatarQAZ** [comment]
On the 0.45 standard API, I was getting a fair amount with 90ish workers (about 100 an hour).  I tried the hashing through Bossland and I have now received 9.... in 24 hours.  

Thanks for the clarification on the gyms.  I understand that it just passively collects.  Thanks!
