### ISSUE TITLE
No IVs stored into db.sqlite

### ISSUE THREAD

**Issue by Rogunix** [Noctem/Monocle#188]
Hello,

By some reason I don't find a way to store IV's or movesets into the database file, stays empty. My actual configuration is:

ENCOUNTER = 'all'

And I manage the notifications (they are working but it only shows pokemon, time and location) by using "ALWAYS_NOTIFY_IDS". I do keep

IGNORE_IVS = True
IGNORE_RARITY = False

Do I need any specific setting to store the IV's and movesets apart from "ENCOUNTER"?

Thanks in advance.

**Comment by MiguelGallegoRO** [comment]
Same problem, I will show my config.py

[config.txt](https://github.com/Noctem/Monocle/files/853459/config.txt)

**Comment by bikthor** [comment]
Same here...

**Comment by MiguelGallegoRO** [comment]
The error happens here, worker.py:

  responses = await self.call(request, action=2.25)

        try:
            pdata = responses['ENCOUNTER']['wild_pokemon']['pokemon_data']
            pokemon['move_1'] = pdata['move_1']
            pokemon['move_2'] = pdata['move_2']
            pokemon['individual_attack'] = pdata.get('individual_attack', 0)
            pokemon['individual_defense'] = pdata.get('individual_defense', 0)
            pokemon['individual_stamina'] = pdata.get('individual_stamina', 0)
        except KeyError:
            self.log.error('Missing Pokemon data in encounter response.')
        self.error_code = '!'


Because in the scan.log..

[2017-03-20 14:27:52][   ERROR][worker-7] Missing Pokemon data in encounter response.
[2017-03-20 14:27:55][   ERROR][worker-7] Missing Pokemon data in encounter response.

All time...

Same problem here #111 


Could be the problem the .get()???
or responses['ENCOUNTER']['wild_pokemon']['pokemon_data']???
