### ISSUE TITLE
Not all pokemons on the map

### ISSUE THREAD

**Issue by GibaPadavan** [Noctem/Monocle#66]
Run it on windows 7.
Use 10 ptc accounts + hashing key + 2capcha.
When I run "python3 scan.py" everything looks good it about 5 minutes it writes that Pokemon found count ~ 500.
But when I run "python3 web.py" there are only about 10 of map. I check both "Pokemon" and "Trash".
If i try to see report - the same small numbers there. "During that session, 17 Pokemon have been seen on an area of about 2 square km." But 705 pokemon found printed in console.
Maybe I do something wrong with config?

**Comment by n30nl1ght** [comment]
Same Problem on Ubuntu 16.04
On the Map are not all Pokemons but in Webhook are they present.

**Comment by evenly-epic-mule** [comment]
nope, this is only because it shows only known spawns on the map
besides that the ~500 found pokemon is just a counter which doesn't check for duplicates

**Comment by Noctem** [comment]
@evenly-epic-mule is right. Displaying Pokémon with unknown expiration times hasn't been implemented yet.

**Comment by DavePlater** [comment]
Are they not shown because without an expiration the map would get cluttered? 
Can we just provide a time for "expire N minutes after seen"? Or something of a way to force-expire?
I have a lot of red circle spawn points...with the area I am most interested in being scanned having all red circles with the "time: ??" markers. So my workers never seem to travel over there?
